// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

contract IdentityVerification {
    
    // The admin is the university system/backend that is allowed to add records
    address public admin;

    // A struct to hold the verification details
    struct VerificationRecord {
        string studentId;      // e.g., "22CIS0329"
        string documentHash;   // The SHA-256 hash of the verification data
        uint256 timestamp;     // When it was recorded
        bool isValid;          // Status of the record
    }

    // Mapping a student ID directly to their verification record
    mapping(string => VerificationRecord) private records;

    // Event that fires when a new record is added
    event RecordAdded(string studentId, string documentHash, uint256 timestamp);

    constructor() {
        // Sets the deployer of the contract as the admin
        admin = msg.sender;
    }

    // Modifier to restrict access to only the admin
    modifier onlyAdmin() {
        require(msg.sender == admin, "Only the admin can perform this action");
        _;
    }

    /**
     * @dev Stores a new verification hash on the blockchain
     * @param _studentId The university index number
     * @param _documentHash The SHA-256 hash generated by the backend
     */
    function storeVerificationHash(string memory _studentId, string memory _documentHash) public onlyAdmin {
        require(!records[_studentId].isValid, "Record already exists for this student");

        records[_studentId] = VerificationRecord({
            studentId: _studentId,
            documentHash: _documentHash,
            timestamp: block.timestamp,
            isValid: true
        });

        emit RecordAdded(_studentId, _documentHash, block.timestamp);
    }

    /**
     * @dev Retrieves a verification record to prove authenticity
     * @param _studentId The university index number
     */
    function getVerificationRecord(string memory _studentId) public view returns (string memory, string memory, uint256, bool) {
        require(records[_studentId].isValid, "No valid record found for this student ID");
        
        VerificationRecord memory record = records[_studentId];
        return (record.studentId, record.documentHash, record.timestamp, record.isValid);
    }
}