// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/**
 * @title IdentityVerification
 * @notice Stores tamper-proof SHA-256 hashes of identity verification events
 *         on the Polygon Amoy testnet (Chain ID 80002).
 *
 * @dev Privacy by design: Only a cryptographic hash of verification metadata
 *      is stored on-chain. No personally identifiable information (PII),
 *      no biometric images, and no raw data are stored — complying with the
 *      Sri Lankan Personal Data Protection Act (PDPA) and GDPR principles.
 *
 * Deployed at: 0xd2b02c6772F504A310fC4cF111780dCe4813a846 (Polygon Amoy)
 * Deployed by: 0x49CcD9584F3F9A1283C80D36bbf501641a0393C5
 */
contract IdentityVerification {

    // ─── Events ──────────────────────────────────────────────────────────────

    /// @notice Emitted each time a new verification hash is anchored.
    event VerificationStored(
        string  indexed requestId,
        string          verificationHash,
        address indexed verifier,
        uint256         timestamp
    );

    // ─── Storage ─────────────────────────────────────────────────────────────

    struct VerificationRecord {
        string  verificationHash; // SHA-256 hex string of the verification metadata
        uint256 timestamp;        // Unix epoch (seconds) when the record was stored
        address verifier;         // Wallet address that submitted the transaction
    }

    /// @dev Maps a verification requestId (Firestore document ID) → its on-chain record
    mapping(string => VerificationRecord) private records;

    // ─── Write ───────────────────────────────────────────────────────────────

    /**
     * @notice Stores a new verification hash permanently on the blockchain.
     * @dev Deployed function selector on Polygon Amoy: 0xbf3be781
     *      This is confirmed by bytecode inspection of the deployed contract.
     *      The Node.js backend uses this selector directly via raw calldata.
     * @param verificationHash  SHA-256 hex string generated by the Node.js backend
     * @param requestId         Firestore Verification_Requests document ID
     */
    function storeVerification(
        string calldata verificationHash,
        string calldata requestId
    ) external {
        records[requestId] = VerificationRecord({
            verificationHash: verificationHash,
            timestamp:        block.timestamp,
            verifier:         msg.sender
        });

        emit VerificationStored(requestId, verificationHash, msg.sender, block.timestamp);
    }

    // ─── Read ────────────────────────────────────────────────────────────────

    /**
     * @notice Retrieves a stored verification record for independent auditing.
     * @param requestId  Firestore Verification_Requests document ID
     * @return verificationHash  The SHA-256 hash anchored on-chain
     * @return timestamp         Unix epoch when the record was stored
     * @return verifier          Address that submitted the anchoring transaction
     */
    function getVerification(string calldata requestId)
        external
        view
        returns (
            string  memory verificationHash,
            uint256        timestamp,
            address        verifier
        )
    {
        VerificationRecord storage r = records[requestId];
        require(bytes(r.verificationHash).length > 0, "No record found for this requestId");
        return (r.verificationHash, r.timestamp, r.verifier);
    }
}
